services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - '9092:9092'
  redis:
    image: redis:7-alpine
  php-api:
    build: ./php-app
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
    ports:
      - '4000:8080'
    depends_on:
      - redis
      - kafka
  php-worker:
    build: ./php-app
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=sim-worker-group
    command: ["php", "bin/worker.php"]
    depends_on:
      - redis
      - kafka
  ws-server:
    build: ./php-app
    command: ["php", "bin/ws-server.php"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8083:8083'
    depends_on:
      - redis
  frontend:
    build: ./client
    ports:
      - '8082:80'
    depends_on:
      - php-api
